---
# yamllint disable rule:line-length
name: build_proxmox_kernel_5.15

on:  # yamllint disable-line rule:truthy
  repository_dispatch:
    types: [trigger_build_TEST]

env:
  CODENAME: ${{ github.event.client_payload.repository.codename }}
  VERSION: ${{ github.event.client_payload.repository.version }}
  ARCH: ${{ github.event.client_payload.repository.arch }}
  REPO_TARGET: pvelati/apt-repository

jobs:
  build:
    strategy:
      matrix:
        BUILD_ARCH: [broadwell, silvermont]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Define BUILD_ARCH
        run: |
          echo ${{ matrix.BUILD_ARCH }} > build_arch
          echo "BUILD_ARCH=$(cat build_arch)" >> $GITHUB_ENV

      - name: print env
        run: |
          echo $CODENAME
          echo $VERSION
          echo $ARCH
          echo $REPO_TARGET

      - name: Configure stuff
        working-directory: ./pve-kernel
        run: |
          echo export BUILD_NUMBER=$(echo $VERSION | grep -o .$)
          export BUILD_NUMBER=$(echo $VERSION | grep -o .$)
          echo export BAUP=${BUILD_ARCH^^}
          export BAUP=${BUILD_ARCH^^}
          sed -i "s/^.*\bKREL=\b.*$/KREL=$BUILD_NUMBER/g" Makefile
          sed -i "s/\EXTRAVERSION=-\${KREL}-pve/EXTRAVERSION=-\${KREL}-pve-$BUILD_ARCH/g" Makefile
          sed -i 's/\-e CONFIG_PAGE_TABLE_ISOLATION/\-e CONFIG_PAGE_TABLE_ISOLATION \\/g' debian/rules
          sed -i '/^\-e CONFIG_PAGE_TABLE_ISOLATION.*/a \-d CONFIG_GENERIC_CPU \\\n\-e CONFIG_MARCHITECTURE \\\n\-e CONFIG_X86_INTEL_USERCOPY \\\n\-e CONFIG_X86_USE_PPRO_CHECKSUM \\\n\-e CONFIG_X86_P6_NOP \\\n\-e CONFIG_CC_HAS_RETURN_THUNK \\\n\-e CONFIG_SPECULATION_MITIGATIONS \\\n\-e CONFIG_RETHUNK \\\n\-e CONFIG_CPU_UNRET_ENTRY \\\n\-e CONFIG_CPU_IBPB_ENTRY \\\n\-e CONFIG_CPU_IBRS_ENTRY' debian/rules
          sed -i "s/CONFIG_MARCHITECTURE/CONFIG_M$BAUP/g" debian/rules
          cat Makefile | grep KREL=
          cat Makefile | grep EXTRAVERSION= | grep -v sed
          cat debian/rules | grep CONFIG_GENERIC_CPU -A1 | grep -v CONFIG_GENERIC_CPU

      - name: Make debs
        working-directory: ./pve-kernel
        run: |
          echo make PVE_BUILD_CFLAGS="-march=$BUILD_ARCH" deb

      - name: Build metapackage
        working-directory: ./metapackage
        run: |
          export CPU_ARCH=$(ls ../pve-kernel/pve-kernel-libc*.deb | cut -d '_' -f3 | cut -d '.' -f1)
          export KERNEL_VERSION=$(ls ../pve-kernel/pve-kernel-libc*.deb | cut -d '_' -f2)
          export META_VERSION=$(date -u +%y%m%d%H%M)
          env
# yamllint enable rule:line-length
