---
# yamllint disable rule:line-length
name: build_proxmox_kernel_5.15

on:  # yamllint disable-line rule:truthy
  repository_dispatch:
    types: [trigger_build_TEST]

env:
  CODENAME: ${{ github.event.client_payload.repository.codename }}
  VERSION: ${{ github.event.client_payload.repository.version }}
  ARCH: ${{ github.event.client_payload.repository.arch }}
  REPO_TARGET: pvelati/apt-repository

jobs:
  build:
    strategy:
      matrix:
        BUILD_ARCH: [broadwell, silvermont]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Define BUILD_ARCH
        run: |
          echo ${{ matrix.BUILD_ARCH }} > build_arch
          echo "BUILD_ARCH=$(cat build_arch)" >> $GITHUB_ENV

      - name: print env
        run: |
          echo $CODENAME
          echo $VERSION
          echo $ARCH
          echo $REPO_TARGET

      - name: Configure stuff
        run: |
          echo export BUILD_NUMBER=$(echo $VERSION | grep -o .$)
          export BUILD_NUMBER=$(echo $VERSION | grep -o .$)
          echo export BAUP=${BUILD_ARCH^^}
          export BAUP=${BUILD_ARCH^^}
          sed -i "s/^.*\bKREL=\b.*$/KREL=$BUILD_NUMBER/g" Makefile
          sed -i "s/\EXTRAVERSION=-\${KREL}-pve/EXTRAVERSION=-\${KREL}-pve-$BUILD_ARCH/g" Makefile
          cat Makefile | grep KREL=
          cat Makefile | grep EXTRAVERSION= | grep -v sed

      - name: Make debs
        run: |
          echo make PVE_BUILD_CFLAGS="-march=$BUILD_ARCH" deb

      - name: Build metapackage
        run: |
          export META_VERSION=$(date -u +%y%m%d%H%M)
          env
# yamllint enable rule:line-length
