---
# yamllint disable rule:line-length
name: test_build_proxmox_kernel_5.15

concurrency: ${{ matrix.BUILD_ARCH }}

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:  # Trigger manually from github

env:
  # OS_CODENAME: ${{ github.event.client_payload.repository.codename }}
  OS_CODENAME: bullseye
  # ARCH: ${{ github.event.client_payload.repository.arch }}
  REPO_TARGET: pvelati/apt-repository
  KERNEL_TARGET: 5.15

jobs:
  build:
    strategy:
      matrix:
        BUILD_ARCH: [broadwell, silvermont]

   steps:
      - name: Wait 10 minutes for ${{ matrix.BUILD_ARCH }}  
        run: |
          sleep i
          echo "Sleeping for 10 minutes ..."
          sleep 10m
          echo "Completed"
