---
name: build_proxmox_kernel_patched_broadwell

on:
  workflow_dispatch:
#  push:
#    branches: [master]

env:
  BUILD_ARCH: broadwell
  REPO_TARGET: pvelati/apt-repository

jobs:
  compile:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pvelati/docker-debian-pve-builder:main
    steps:
      - name: Show space
        run: |
         df -h
         sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
         sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Test clean
        run: |
         df -h
         # echo
         # rm -rf /usr/share/dotnet
         # rm -rf /opt/ghc
         # rm -rf "/usr/local/share/boost"
         # rm -rf "$AGENT_TOOLSDIRECTORY"
         # echo
         # df -h

      - uses: actions/checkout@v3

      - name: Clone pve-kernel repo branch master
        run: |
          git clone --depth 1 --branch pve-kernel-5.15 https://git.proxmox.com/git/pve-kernel.git

      - name: Add patch
        working-directory: ./pve-kernel
        run: |
          wget -O patches/kernel/0032-add-uarch.patch https://raw.githubusercontent.com/graysky2/kernel_compiler_patch/master/more-uarches-for-kernel-5.15-5.16.patch

      - name: Configure stuff
        working-directory: ./pve-kernel
        run: |
          sed -i 's/\EXTRAVERSION=-${KREL}-pve/EXTRAVERSION=-${KREL}-pve-broadwell/g' Makefile
          sed -i 's/\-e CONFIG_PAGE_TABLE_ISOLATION/\-e CONFIG_PAGE_TABLE_ISOLATION \\/g' debian/rules
          sed -i '/^\-e CONFIG_PAGE_TABLE_ISOLATION.*/a \-d CONFIG_GENERIC_CPU \\\n\-e CONFIG_MBROADWELL \\\n\-e CONFIG_X86_INTEL_USERCOPY \\\n\-e CONFIG_X86_USE_PPRO_CHECKSUM \\\n\-e CONFIG_X86_P6_NOP \\\n\-e CONFIG_CC_HAS_RETURN_THUNK \\\n\-e CONFIG_SPECULATION_MITIGATIONS \\\n\-e CONFIG_RETHUNK \\\n\-e CONFIG_CPU_UNRET_ENTRY \\\n\-e CONFIG_CPU_IBPB_ENTRY \\\n\-e CONFIG_CPU_IBRS_ENTRY' debian/rules

      - name: Make debs
        working-directory: ./pve-kernel
        run: |
          make PVE_BUILD_CFLAGS="-march=broadwell" deb

      - name: Build metapackage
        working-directory: ./metapackage
        run: |
         KERNEL_VERSION=$(ls ../pve-kernel/pve-kernel-libc*.deb | cut -d '_' -f2)
         CURRENT_METAVERSION=$(cat VERSION)
         META_VERSION=$(( CURRENT_METAVERSION + 1 ))
         echo $META_VERSION > VERSION
         cat ns-control-TEMPLATE | envsubst > ns-control
         equivs-build ns-control

      - name: Release packages
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          tag_name: broadwell
          files: |
            pve-kernel/*.deb
            metapackage/*.deb

      - name: Trigger repository action
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${secrets.GH_TOKEN_TRIGGER}" https://api.github.com/repos/${env.REPO_TARGET}/dispatches \
           -d '{"event_type":"trigger_build","client_payload":{"repository":{"owner":"${GITHUB_REPOSITORY_OWNER}","name":"${GITHUB_REPOSITORY#*/}","tag":"${BUILD_ARCH}"}}}'

      - name: Commit and push updated metapackage version
        run: |
          git init
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add metapackage/VERSION
          git commit -am "GitHub Action update metapackage version"
          git push
