---
# yamllint disable rule:line-length
name: test_build_proxmox_kernel_5.15

run-name: ${{ github.event.client_payload.repository.arch }}
concurrency: ${{ github.event.client_payload.repository.arch }}

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:  # Trigger manually from github
  repository_dispatch:
    types: [trigger_build_wait]

env:
  # OS_CODENAME: ${{ github.event.client_payload.repository.codename }}
  OS_CODENAME: bullseye
  # ARCH: ${{ github.event.client_payload.repository.arch }}
  REPO_TARGET: pvelati/apt-repository
  KERNEL_TARGET: 5.15
  BUILD_ARCH: ${{ github.event.client_payload.repository.arch }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pvelati/docker-debian-pve-builder:main
      volumes:
        - /opt:/sys_root/opt
        - /usr/local/lib:/sys_root/usr/local/lib
        - /usr/local/share:/sys_root/usr/local/share
        - /usr/share:/sys_root/usr/share
    steps:
#       - name: Wait 10 minutes for ${{ env.BUILD_ARCH }}
#         run: |
#           echo "Sleeping for 10 minutes ..."
#           sleep 10m
#           echo "Completed"
      - name: Exec script
        run: |
          ./scripts/build.sh

      - name: Print other variables
        run: |
          echo "KERNEL_VERSION_GH=${{ env.KERNEL_VERSION }}"
          echo "META_VERSION=${{ env.META_VERSION }}"
