---
# yamllint disable rule:line-length
name: test_build_proxmox_kernel_5.15_${{ github.event.client_payload.repository.arch }}

concurrency: ${{ github.event.client_payload.repository.arch }}

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:  # Trigger manually from github
  repository_dispatch:
    types: [trigger_build_wait]

env:
  # OS_CODENAME: ${{ github.event.client_payload.repository.codename }}
  OS_CODENAME: bullseye
  # ARCH: ${{ github.event.client_payload.repository.arch }}
  REPO_TARGET: pvelati/apt-repository
  KERNEL_TARGET: 5.15

jobs:
  build:
    strategy:
      matrix:
        BUILD_ARCH: [broadwell, silvermont]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pvelati/docker-debian-pve-builder:main

    steps:
      - name: Wait 10 minutes for ${{ matrix.BUILD_ARCH }}  
        run: |
          echo "Sleeping for 10 minutes ..."
          sleep 10m
          echo "Completed"
