name: test-go-build-exection

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GH_TOKEN_TRIGGER: ${{ secrets.GH_TOKEN_TRIGGER }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build

    - name: Run
      run: ./github-actions-sandbox
